### ISSUE TITLE
Virgil-Bot Beans~

### ISSUE THREAD

**Issue by Ambaaargh** [juan0tron/gem-exchange-bot#1]
These are pretty much all standard basic "insert !code, recieve dumbass image :B" Obviously if any of the names seem like they would be better renamed to something else command go for eet~

(!Boi ) https://cdn.discordapp.com/attachments/293878589731110916/349721254326042624/Boi.png

(!Salad ) https://cdn.discordapp.com/attachments/293878589731110916/349721329693360136/Salad.png

(!Magic ) https://cdn.discordapp.com/attachments/293878589731110916/349721383867252739/Maaagic.png

(!NoPLZ ) https://cdn.discordapp.com/attachments/293878589731110916/349721427760513035/NoPlz.png

(!MOAR ) https://cdn.discordapp.com/attachments/293878589731110916/349721448123990018/MOAR.png

(!OhSnap ) https://cdn.discordapp.com/attachments/293878589731110916/349721467614789642/Ohhhhh.png

(!Gaaay ) https://cdn.discordapp.com/attachments/293878589731110916/349879470196523008/Gaaaay.png

**Comment by glitchwolfe** [comment]
DIMMA DONE
