### ISSUE TITLE
!motivate

### ISSUE THREAD

**Issue by Ambaaargh** [juan0tron/gem-exchange-bot#10]
For DiscordChan:

The general idea is having these images in a bin that gets randomly pulled when the prompt is triggered.  So random feel goods.  Got 10 so far for the pool. Figure we can add more as we go.

https://cdn.discordapp.com/attachments/365243703914135564/366066263425941505/D_M1.png
https://cdn.discordapp.com/attachments/365243703914135564/366066284229820416/D_M2.png
https://cdn.discordapp.com/attachments/365243703914135564/366066302466523139/D_M3.png
https://cdn.discordapp.com/attachments/365243703914135564/366066324260257792/D_M4.png
https://cdn.discordapp.com/attachments/365243703914135564/366066794974281738/D_M5.png
https://cdn.discordapp.com/attachments/365243703914135564/366070274413559808/D_M6.png
https://cdn.discordapp.com/attachments/365243703914135564/366070299319468032/D_M7.png
https://cdn.discordapp.com/attachments/365243703914135564/366072344097193999/D_M8.png
https://cdn.discordapp.com/attachments/365243703914135564/366073773838827521/HythGood.png
https://cdn.discordapp.com/attachments/365243703914135564/366073788573417472/HythGood2.png

**Comment by glitchwolfe** [comment]
These ones have been added!
