### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by Ambaaargh** [juan0tron/gem-exchange-bot#11]
For when someone new comes into the discord:

:sparkles:  Please give a friendly welcome to our newest member: (Name of person)!! :sparkles: 
Thank you for joining Gem-Exchange!  We're glad you chose to give our community a try.  If you have any questions or concerns, please feel free to contact any of the mods (Doritos Locos Tacos) or admins (Cheesy Gordita Crunches) and we will try to get back to you asap!  If you're new, please consider checking out the server rules at <http://thegemexchange.net/discord> and perhaps writing out an intro for yourself at #intro_profiles so we can get to know you better. Thank you and enjoy your stay. We look forward to talking to you!
(Insert welcome image here)
https://cdn.discordapp.com/attachments/293878589731110916/364931784296628235/D_Greeting.png

If you feel you can come up with a way to streamline this and make it more polished, by all means. I tried to keep from having it get too massive since I figure no one wants to see a giant paragraph greeting them. XD

**Comment by glitchwolfe** [comment]
Donezo!
