### ISSUE TITLE
ADD SHIT TO THE BOT

### ISSUE THREAD

**Issue by Clonecakes** [juan0tron/gem-exchange-bot#12]
**!Feedback** --Link To--> https://docs.google.com/forms/d/1V6WzrkN-D3N_YOhIuOU74YntvpWcyxYZfy3dUe951X8/viewform?edit_requested=true
**!Edit** --Link To--> https://docs.google.com/forms/d/e/1FAIpQLSc0zqv3OeM6HdkLn-iWCb01UPSETTThykJagoY44mgpcH3_bw/viewform
**!Egg** --Link To--> https://cdn.discordapp.com/attachments/254287968334905365/416338875187724288/Trying.png
**!Sweats** --Link To--> https://cdn.discordapp.com/attachments/254287968334905365/416343125162721280/Sweats.png

**Comment by glitchwolfe** [comment]
!sweats done

**Comment by glitchwolfe** [comment]
!edit and !feedback done

**Comment by glitchwolfe** [comment]
!egg is actually !trying so we done here
