### ISSUE TITLE
Disable multiple !!! commands?

### ISSUE THREAD

**Issue by milay** [juan0tron/gem-exchange-bot#2]
Not sure if that is feasable, especially if it's just a really minor annoyance, but sometimes people make excited posts with two or three ! at the beginning, and Virgil Bot reacts with a "I don't know that command"

It's okay when Virgil says !boy is not a valid command, but is it possible exclude such posts from any reaction?

![screen_ 2017-08-25_4553](https://user-images.githubusercontent.com/2557428/29722422-fbd3bcf4-89c0-11e7-895e-2b3328644763.jpg)

**Comment by glitchwolfe** [comment]
Fixed in edfd7e1! (also that's hilarious)
